apiVersion: v1
kind: PersistentVolume
metadata:
  name: jekyll-pv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jeongjinseo/JekyllBlog/docs"
  persistentVolumeReclaimPolicy: Retain
